# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backup_master.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'backup_master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61\x63kup_master.proto\x12\x06\x62\x61\x63kup\"$\n\tFileTable\x12\x17\n\x0f\x66ile_table_json\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2v\n\rBackUpService\x12\x30\n\x0cgetFileTable\x12\r.backup.Empty\x1a\x11.backup.FileTable\x12\x33\n\x0fupdateFileTable\x12\x11.backup.FileTable\x1a\r.backup.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILETABLE']._serialized_start=31
  _globals['_FILETABLE']._serialized_end=67
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_BACKUPSERVICE']._serialized_start=78
  _globals['_BACKUPSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
