# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backup_master_pb2 as backup__master__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in backup_master_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BackUpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFileTable = channel.unary_unary(
                '/backup.BackUpService/getFileTable',
                request_serializer=backup__master__pb2.Empty.SerializeToString,
                response_deserializer=backup__master__pb2.FileTable.FromString,
                _registered_method=True)
        self.updateFileTable = channel.unary_unary(
                '/backup.BackUpService/updateFileTable',
                request_serializer=backup__master__pb2.FileTable.SerializeToString,
                response_deserializer=backup__master__pb2.Empty.FromString,
                _registered_method=True)


class BackUpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFileTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateFileTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackUpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getFileTable': grpc.unary_unary_rpc_method_handler(
                    servicer.getFileTable,
                    request_deserializer=backup__master__pb2.Empty.FromString,
                    response_serializer=backup__master__pb2.FileTable.SerializeToString,
            ),
            'updateFileTable': grpc.unary_unary_rpc_method_handler(
                    servicer.updateFileTable,
                    request_deserializer=backup__master__pb2.FileTable.FromString,
                    response_serializer=backup__master__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backup.BackUpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('backup.BackUpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackUpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFileTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backup.BackUpService/getFileTable',
            backup__master__pb2.Empty.SerializeToString,
            backup__master__pb2.FileTable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateFileTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backup.BackUpService/updateFileTable',
            backup__master__pb2.FileTable.SerializeToString,
            backup__master__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
