# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x06sample\"9\n\rSampleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\x05\x63ount\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_count\"!\n\x0eSampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x01\n\rSampleService\x12<\n\tGetSample\x12\x15.sample.SampleRequest\x1a\x16.sample.SampleResponse\"\x00\x12\x44\n\x0fGetSampleStream\x12\x15.sample.SampleRequest\x1a\x16.sample.SampleResponse\"\x00\x30\x01\x12S\n\x1cGetSampleStreamBidirectional\x12\x15.sample.SampleRequest\x1a\x16.sample.SampleResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLEREQUEST']._serialized_start=24
  _globals['_SAMPLEREQUEST']._serialized_end=81
  _globals['_SAMPLERESPONSE']._serialized_start=83
  _globals['_SAMPLERESPONSE']._serialized_end=116
  _globals['_SAMPLESERVICE']._serialized_start=119
  _globals['_SAMPLESERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
