# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sample_pb2 as sample__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sample_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSample = channel.unary_unary(
                '/sample.SampleService/GetSample',
                request_serializer=sample__pb2.SampleRequest.SerializeToString,
                response_deserializer=sample__pb2.SampleResponse.FromString,
                _registered_method=True)
        self.GetSampleStream = channel.unary_stream(
                '/sample.SampleService/GetSampleStream',
                request_serializer=sample__pb2.SampleRequest.SerializeToString,
                response_deserializer=sample__pb2.SampleResponse.FromString,
                _registered_method=True)
        self.GetSampleStreamBidirectional = channel.stream_stream(
                '/sample.SampleService/GetSampleStreamBidirectional',
                request_serializer=sample__pb2.SampleRequest.SerializeToString,
                response_deserializer=sample__pb2.SampleResponse.FromString,
                _registered_method=True)


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleStreamBidirectional(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSample,
                    request_deserializer=sample__pb2.SampleRequest.FromString,
                    response_serializer=sample__pb2.SampleResponse.SerializeToString,
            ),
            'GetSampleStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSampleStream,
                    request_deserializer=sample__pb2.SampleRequest.FromString,
                    response_serializer=sample__pb2.SampleResponse.SerializeToString,
            ),
            'GetSampleStreamBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.GetSampleStreamBidirectional,
                    request_deserializer=sample__pb2.SampleRequest.FromString,
                    response_serializer=sample__pb2.SampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample.SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sample.SampleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sample.SampleService/GetSample',
            sample__pb2.SampleRequest.SerializeToString,
            sample__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sample.SampleService/GetSampleStream',
            sample__pb2.SampleRequest.SerializeToString,
            sample__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleStreamBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sample.SampleService/GetSampleStreamBidirectional',
            sample__pb2.SampleRequest.SerializeToString,
            sample__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
